#!/usr/bin/env python3
"""Legal Qwen-only boxed-answer pass.

This module is intentionally narrow:

- it uses only ``Qwen/Qwen3-4B-Thinking-2507`` or a LoRA adapter whose
  ``adapter_config.json`` names that exact base model;
- it runs an additional model generation pass over an existing model response;
- it renders Qwen chat prompts with thinking disabled by default;
- it does not call solvers, calculators, symbolic math, external APIs, web
  services, or deterministic answer-computing repair code.

The pass may reformat, extract, verify, or repair by asking the allowed Qwen
model itself. Any final answer selection comes from model output, not Python
math.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional

try:
    from tqdm import tqdm
except ImportError:  # pragma: no cover - dependency-light CLI/help mode.
    def tqdm(iterable, **_: object):
        return iterable


ROOT = Path(__file__).resolve().parent
DESIGNATED_MODEL = "Qwen/Qwen3-4B-Thinking-2507"

SYSTEM_BOXED = (
    "You are the designated Qwen3-4B math model running a legal model-only "
    "finalization pass. Use only your own model-internal reasoning from the "
    "provided problem, answer choices, and previous model response. Do not use "
    "tools, code, calculators, APIs, lookup tables, web search, or external "
    "references. Your entire assistant message must be exactly one line of the "
    "form \\boxed{answer}. The text inside the box must be only the final "
    "answer, not reasoning. Do not include sentences, derivations, bullet "
    "lists, labels, or any text before or after the box."
)

MODE_INSTRUCTIONS = {
    "format": (
        "Do not solve from scratch. Preserve the mathematical meaning of the "
        "previous response, but fix answer formatting: one \\boxed{} wrapper, "
        "clean LaTeX, correct comma separation for multiple answer slots, no "
        "surrounding prose, and no reasoning inside the box."
    ),
    "extract": (
        "Do not solve from scratch unless the previous response is ambiguous. "
        "Extract the final answer that the previous response most clearly "
        "intended, then put only that answer inside \\boxed{}. Do not include "
        "the reasoning or explanation."
    ),
    "repair": (
        "Check the previous response using only your own reasoning. If it is "
        "already correct, keep its final answer. If it contains a clear mistake, "
        "repair it. Return only the corrected final answer inside \\boxed{}, "
        "with no explanation."
    ),
    "structured": (
        "Audit the previous response for common final-answer failures: wrong "
        "or missing MCQ letter, option-text/letter mismatch, missing answer "
        "slots, final boxed answer mismatch, unit/rounding/format slips, and "
        "ordinary reasoning mistakes. Repair only through your own model "
        "reasoning and return one \\boxed{} answer with no explanation."
    ),
    "solve": (
        "Solve the problem directly using only your own model reasoning, then "
        "return only the complete final answer inside one \\boxed{}."
    ),
    "diagnose": (
        "Choose the single best repair lane for a following Qwen pass. Return "
        "only lane name, slot count if relevant, and minimal problem/answer "
        "facts inside one \\boxed{}."
    ),
    "specialized": (
        "Use the supplied Qwen diagnosis plus the specialized prompt rubric to "
        "repair the previous answer through your own model reasoning. Return "
        "only one final answer inside \\boxed{}."
    ),
    "choose": (
        "Compare the supplied candidate answers, all of which were generated by "
        "the allowed Qwen/Qwen-derived pipeline. Use only your own model-internal "
        "reasoning from the problem, answer choices, and candidate answers to "
        "choose or lightly repair the most likely correct final answer. "
        "Return only that final answer inside \\boxed{}."
    ),
}

LEGAL_REPAIR_RUBRIC = """\
Legal model-only repair rubric:
- Never call tools, code, calculators, APIs, web search, lookup tables, or external references.
- Do all checking with your own model-internal math reasoning from the supplied prompt and previous answer.
- If the previous answer already contains the correct mathematical value but in the wrong format, rewrite it legally.
- For MCQ rows, map the model's intended value or conclusion to exactly one option letter. Do not output option text.
- For multi-blank rows, count every requested [ANS] slot and return all answers in the original order.
- Prefer the final mathematical conclusion over exploratory intermediate boxed values.
- Repair common model failure classes: option-value/letter mismatch, missing answer slots, final boxed-answer mismatch, unit/rounding/format slips, arithmetic/algebra/statistics/sequence/combinatorics slips, and verbose answers that need one concise boxed response.
- When uncertain, preserve the previous answer's intended conclusion rather than inventing unsupported detail.
"""

SPECIALIZED_REPAIR_RECIPES = """\
Specialized legal repair recipes. Pick the lane matching the Qwen diagnosis and problem.

General output contract:
- Return exactly one final answer inside one \\boxed{}.
- For multiple [ANS] slots, return every slot in the original order, separated by commas.
- Do not round unless the problem explicitly asks for rounding or the previous answer only supports a rounded conclusion.
- Prefer exact answer-readable expressions over rounded decimals when the prompt accepts exact form.
- No tools, code, calculators, APIs, lookup tables, or external references.

Lane MULTI_SLOT_NUMERIC:
- Count [ANS] slots in the problem. The boxed answer must contain exactly that many comma-separated values.
- If the previous answer gave separate part answers, merge them into one box in order.

Lane UNIT_CONVERSION:
- Keep the requested unit order exactly. Use the model's own math reasoning to convert and preserve exact forms when useful.

Lane EXPONENTIAL_DECAY:
- Track the period, decay/growth factor, and requested time unit. Return the requested expression or numeric answer only.

Lane NEWTON_COOLING:
- Track ambient temperature, initial value, calibration time/value, target value, and requested time unit.

Lane FUNCTION_MODEL_MULTI_PART:
- Evaluate requested finite values, inverse/time questions, and limiting/asymptotic values in the slot order requested.

Lane TRIG_GENERAL_SOLUTION:
- Preserve principal-angle plus-period answer format when a general solution is requested.

Lane STATS_TABLE_STANDARD_DEVIATION:
- Fill every table slot, including deviations, squared deviations, sum, variance denominator, and final standard deviation.

Lane CHI_SQUARE_TEST:
- Return statistic, critical value or p-value, and conclusion only if the prompt asks for those slots.

Lane FRACTION_SIMPLIFY:
- Return a reduced fraction when the prompt asks for a reduced fraction.

Lane BERNSTEIN_POLYNOMIALS:
- Preserve coefficient, power of t, and power of (1-t) for every requested polynomial in order.

Lane STEP_COST_FUNCTION:
- Preserve symbolic cost/rate slots, rounding direction slots, and domain/range slots separately.

Lane ALGEBRA_EXPRESSION:
- Preserve variables, exact powers, radicals, fractions, intervals, tuples, and requested container format.

Lane FORMAT_ONLY:
- Do not change the previous answer's mathematical value. Remove prose and wrap the final answer in exactly one \\boxed{}.

Lane MCQ_OPTION_MATCH:
- For multiple-choice problems, output the option letter, not option text. If the previous answer names option text, match it to the listed options.

Lane FULL_RESOLVE:
- If no narrow lane fits, solve with model-internal reasoning only and return the concise boxed final answer.
"""


def validate_competition_model(model: str) -> None:
    """Allow only the designated base model or LoRA adapters derived from it."""
    if model == DESIGNATED_MODEL:
        return

    model_path = Path(model)
    adapter_config = model_path / "adapter_config.json"
    if adapter_config.exists():
        try:
            config = json.loads(adapter_config.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"Invalid adapter_config.json for {model}: {exc}") from exc
        if config.get("base_model_name_or_path") == DESIGNATED_MODEL:
            return

    raise ValueError(
        "qwen.py may only use Qwen/Qwen3-4B-Thinking-2507 or a LoRA adapter "
        "whose adapter_config.json names that base model. "
        f"Got: {model}"
    )


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        raise FileNotFoundError(path)
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def load_by_id(path: Path) -> dict[int, dict]:
    return {int(row["id"]): row for row in load_jsonl(path)}


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    with tmp_path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    tmp_path.replace(path)


def load_id_filter(ids: str, ids_file: Optional[Path]) -> set[int] | None:
    raw_values: list[str] = []
    if ids:
        raw_values.extend(part.strip() for part in ids.split(","))
    if ids_file is not None:
        for line in ids_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            raw_values.extend(part.strip() for part in line.split(","))
    values = [value for value in raw_values if value]
    return {int(value) for value in values} if values else None


def format_options(options: Optional[list]) -> str:
    if not options:
        return ""
    labels = [chr(65 + idx) for idx in range(len(options))]
    return "\n".join(f"{label}. {str(option).strip()}" for label, option in zip(labels, options))


def trim_previous_response(response: str, base_tail_chars: int) -> str:
    response = response or ""
    if base_tail_chars > 0 and len(response) > base_tail_chars:
        return response[-base_tail_chars:]
    return response


def load_candidate_results(specs: list[str]) -> dict[str, dict[int, dict]]:
    candidates: dict[str, dict[int, dict]] = {}
    for spec in specs:
        if "=" not in spec:
            raise ValueError(
                "--candidate-results entries must be name=path, "
                f"got {spec!r}"
            )
        name, raw_path = spec.split("=", 1)
        name = name.strip()
        if not name:
            raise ValueError(f"Empty candidate name in {spec!r}")
        path = Path(raw_path)
        if not path.exists():
            print(f"WARNING: skipping missing candidate result {name}={path}", file=sys.stderr)
            continue
        candidates[name] = load_by_id(path)
    return candidates


def format_candidate_block(
    item_id: int,
    previous_row: dict,
    candidate_results: dict[str, dict[int, dict]],
    candidate_tail_chars: int,
) -> str:
    rows: list[tuple[str, dict]] = [("base", previous_row)]
    rows.extend(
        (name, by_id[item_id])
        for name, by_id in candidate_results.items()
        if item_id in by_id
    )
    chunks = []
    seen: set[str] = set()
    for name, row in rows:
        response = trim_previous_response(str(row.get("response", "")), candidate_tail_chars)
        if not response.strip():
            continue
        key = response.strip()
        if key in seen:
            continue
        seen.add(key)
        chunks.append(f"Candidate {name}:\n{response}")
    if chunks:
        return "\n\n".join(chunks)
    return r"Candidate base:\n\boxed{}"


def build_messages(
    item: dict,
    previous_row: dict,
    mode: str,
    base_tail_chars: int,
    candidate_results: dict[str, dict[int, dict]] | None = None,
    candidate_tail_chars: int = 900,
) -> list[dict]:
    previous_response = trim_previous_response(str(previous_row.get("response", "")), base_tail_chars)
    original_response = trim_previous_response(
        str(previous_row.get("base_response", previous_response)),
        base_tail_chars,
    )
    options_text = format_options(item.get("options"))
    instruction = MODE_INSTRUCTIONS[mode]

    if mode == "choose" and options_text:
        candidate_block = format_candidate_block(
            int(item["id"]),
            previous_row,
            candidate_results or {},
            candidate_tail_chars,
        )
        user_prompt = (
            f"{LEGAL_REPAIR_RUBRIC}\n\n"
            f"{instruction}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Answer choices:\n"
            f"{options_text}\n\n"
            "Candidate answers:\n"
            f"{candidate_block}\n\n"
            "Choose the best final option. If a candidate's option text and "
            "letter disagree, use your own model reasoning to resolve the "
            "choice. Output only one boxed option letter."
        )
    elif mode == "choose":
        candidate_block = format_candidate_block(
            int(item["id"]),
            previous_row,
            candidate_results or {},
            candidate_tail_chars,
        )
        user_prompt = (
            f"{LEGAL_REPAIR_RUBRIC}\n\n"
            f"{instruction}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Candidate answers:\n"
            f"{candidate_block}\n\n"
            "Choose or lightly repair the best final answer. If there are "
            "multiple [ANS] blanks or parts, include every requested answer in "
            "original order inside one \\boxed{}, separated by commas. Output "
            "only one boxed answer line."
        )
    elif mode == "diagnose" and options_text:
        user_prompt = (
            f"{instruction}\n\n"
            "Allowed lane names: MCQ_OPTION_MATCH, FORMAT_ONLY, FULL_RESOLVE.\n"
            "Return only: \\boxed{LANE=<lane>; FACTS=<brief facts from the problem/previous answer>}.\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Answer choices:\n"
            f"{options_text}\n\n"
            "Previous model response:\n"
            f"{previous_response}"
        )
    elif mode == "diagnose":
        user_prompt = (
            f"{instruction}\n\n"
            "Allowed lane names: MULTI_SLOT_NUMERIC, UNIT_CONVERSION, "
            "EXPONENTIAL_DECAY, NEWTON_COOLING, FUNCTION_MODEL_MULTI_PART, "
            "TRIG_GENERAL_SOLUTION, STATS_TABLE_STANDARD_DEVIATION, CHI_SQUARE_TEST, "
            "FRACTION_SIMPLIFY, BERNSTEIN_POLYNOMIALS, STEP_COST_FUNCTION, "
            "ALGEBRA_EXPRESSION, FORMAT_ONLY, FULL_RESOLVE.\n"
            "Return only: \\boxed{LANE=<lane>; SLOTS=<number of [ANS] slots>; "
            "FACTS=<minimal useful facts from the problem and previous answer>}.\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Previous model response:\n"
            f"{previous_response}"
        )
    elif mode == "specialized" and options_text:
        user_prompt = (
            f"{SPECIALIZED_REPAIR_RECIPES}\n\n"
            "Qwen diagnosis from the previous pass:\n"
            f"{previous_response}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Answer choices:\n"
            f"{options_text}\n\n"
            "Original previous answer to repair:\n"
            f"{original_response}\n\n"
            "Use the diagnosed lane and matching recipe. Your entire response "
            "must be one boxed option letter."
        )
    elif mode == "specialized":
        user_prompt = (
            f"{SPECIALIZED_REPAIR_RECIPES}\n\n"
            "Qwen diagnosis from the previous pass:\n"
            f"{previous_response}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Original previous answer to repair:\n"
            f"{original_response}\n\n"
            "Use the diagnosed lane and matching recipe. Your entire response "
            "must be one boxed final answer."
        )
    elif mode == "structured" and options_text:
        user_prompt = (
            f"{LEGAL_REPAIR_RUBRIC}\n\n"
            f"{instruction}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Answer choices:\n"
            f"{options_text}\n\n"
            "Previous model response:\n"
            f"{previous_response}\n\n"
            "If this is multiple choice, output only the final option letter "
            "inside \\boxed{}."
        )
    elif mode == "structured":
        user_prompt = (
            f"{LEGAL_REPAIR_RUBRIC}\n\n"
            f"{instruction}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Previous model response:\n"
            f"{previous_response}\n\n"
            "If there are multiple [ANS] blanks or parts, include every requested "
            "answer in original order inside one \\boxed{}, separated by commas."
        )
    elif options_text:
        user_prompt = (
            f"{instruction}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Answer choices:\n"
            f"{options_text}\n\n"
            "Previous model response:\n"
            f"{previous_response}\n\n"
            "If this is multiple choice, output only the final option letter "
            "inside \\boxed{}. Your entire response must be one line and must "
            "match exactly: \\boxed{A}, \\boxed{B}, etc."
        )
    else:
        user_prompt = (
            f"{instruction}\n\n"
            "Problem:\n"
            f"{item['question']}\n\n"
            "Previous model response:\n"
            f"{previous_response}\n\n"
            "If there are multiple [ANS] blanks or parts, include every requested "
            "answer in original order inside one \\boxed{}, separated by commas. "
            "Your entire response must be one boxed answer line only."
        )

    return [
        {"role": "system", "content": SYSTEM_BOXED},
        {"role": "user", "content": user_prompt},
    ]


def render_prompt(tokenizer, messages: list[dict], disable_thinking: bool = True) -> str:
    kwargs = {
        "tokenize": False,
        "add_generation_prompt": True,
        "enable_thinking": not disable_thinking,
    }
    try:
        rendered = tokenizer.apply_chat_template(messages, **kwargs)
    except TypeError:
        kwargs.pop("enable_thinking", None)
        rendered = tokenizer.apply_chat_template(messages, **kwargs)
    if disable_thinking and rendered.rstrip().endswith("<think>"):
        rendered = rendered.rstrip() + "\n</think>\n\n"
    return rendered


def extract_last_boxed(text: str) -> str | None:
    marker = r"\boxed{"
    idx = text.rfind(marker)
    if idx < 0:
        return None
    i = idx + len(marker)
    depth = 1
    out: list[str] = []
    while i < len(text) and depth > 0:
        ch = text[i]
        if ch == "{":
            depth += 1
            out.append(ch)
        elif ch == "}":
            depth -= 1
            if depth:
                out.append(ch)
        else:
            out.append(ch)
        i += 1
    if depth:
        return None
    return "".join(out).strip()


def coerce_boxed_response(response: str) -> str:
    """Box the model's own final string without computing or choosing answers."""
    response = (response or "").strip()
    boxed = extract_last_boxed(response)
    if boxed is not None:
        return rf"\boxed{{{boxed}}}"
    if not response:
        return r"\boxed{}"
    for prefix in ("Final answer:", "Final Answer:", "Answer:", "The answer is"):
        if response.startswith(prefix):
            response = response[len(prefix) :].strip()
    return rf"\boxed{{{response}}}"


def apply_boxed_prefill(prompt: str) -> str:
    return prompt + r"\boxed{"


def restore_boxed_prefill(response: str) -> str:
    response = (response or "").strip()
    if response.startswith(r"\boxed{"):
        restored = response
    else:
        restored = r"\boxed{" + response
    if restored.startswith(r"\boxed{") and restored.count("{") == restored.count("}") + 1:
        restored += "}"
    return restored


def load_transformers_model(model_name: str, gpu_id: str | None):
    if gpu_id is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = gpu_id
    os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    adapter_config = Path(model_name) / "adapter_config.json"
    if adapter_config.exists():
        from peft import PeftModel

        config = json.loads(adapter_config.read_text(encoding="utf-8"))
        base_model_name = config["base_model_name_or_path"]
        try:
            tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        except Exception:
            tokenizer = AutoTokenizer.from_pretrained(base_model_name, trust_remote_code=True)
        base_model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            trust_remote_code=True,
            quantization_config=bnb_config,
            device_map="auto",
            attn_implementation="eager",
        )
        model = PeftModel.from_pretrained(base_model, model_name).merge_and_unload()
    else:
        tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            trust_remote_code=True,
            quantization_config=bnb_config,
            device_map="auto",
            attn_implementation="eager",
        )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"
    model.eval()
    return model, tokenizer


def load_vllm_model(model_name: str, args):
    if args.gpu_id is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu_id

    from transformers import AutoTokenizer
    from vllm import LLM
    from vllm.lora.request import LoRARequest

    adapter_config = Path(model_name) / "adapter_config.json"
    lora_request = None
    if adapter_config.exists():
        config = json.loads(adapter_config.read_text(encoding="utf-8"))
        load_model_name = config["base_model_name_or_path"]
        try:
            tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        except Exception:
            tokenizer = AutoTokenizer.from_pretrained(load_model_name, trust_remote_code=True)
        lora_request = LoRARequest("qwen_pass_adapter", 1, str(Path(model_name)))
    else:
        load_model_name = model_name
        tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    llm = LLM(
        model=load_model_name,
        trust_remote_code=True,
        dtype=args.dtype,
        max_model_len=args.max_model_len,
        gpu_memory_utilization=args.gpu_memory_utilization,
        max_num_seqs=args.vllm_max_num_seqs,
        max_num_batched_tokens=args.vllm_max_num_batched_tokens,
        enable_lora=lora_request is not None,
        max_lora_rank=args.vllm_max_lora_rank,
    )
    return llm, tokenizer, lora_request


def select_items(args) -> tuple[list[dict], dict[int, dict]]:
    items = load_jsonl(args.data)
    base_by_id = load_by_id(args.base_results)
    if args.question_filter != "all":
        want_mcq = args.question_filter == "mcq"
        items = [item for item in items if bool(item.get("options")) == want_mcq]
    id_filter = load_id_filter(args.ids, args.ids_file)
    if id_filter is not None:
        items = [item for item in items if int(item["id"]) in id_filter]
    items = [item for item in items if int(item["id"]) in base_by_id]
    if args.start_index > 0:
        items = items[args.start_index :]
    if args.limit > 0:
        items = items[: args.limit]
    return items, base_by_id


def run_qwen_pass(args) -> int:
    validate_competition_model(args.model)
    items, base_by_id = select_items(args)
    candidate_results = load_candidate_results(args.candidate_results)
    if args.mode == "choose" and not candidate_results:
        print(
            "WARNING: --mode choose has no available candidate results; "
            "falling back to Qwen verification of --base-results only.",
            file=sys.stderr,
        )

    existing: list[dict] = []
    done_ids: set[int] = set()
    if args.resume and args.output.exists():
        existing = load_jsonl(args.output)
        done_ids = {int(row["id"]) for row in existing}
    pending = [item for item in items if int(item["id"]) not in done_ids]
    print(f"Loaded {len(items)} eligible items; pending {len(pending)}", flush=True)
    if not pending:
        return 0

    if args.backend == "vllm":
        from vllm import SamplingParams

        model, tokenizer, lora_request = load_vllm_model(args.model, args)
        sampling_params = SamplingParams(
            max_tokens=args.max_tokens,
            temperature=0.0,
            seed=42,
            stop=["\n", "<|im_end|>"] if args.boxed_prefill else None,
        )
    else:
        model, tokenizer = load_transformers_model(args.model, args.gpu_id)
        sampling_params = None
        lora_request = None

    all_rows = list(existing)
    for start in tqdm(range(0, len(pending), args.batch_size), desc="Qwen pass"):
        batch = pending[start : start + args.batch_size]
        prompts = [
            render_prompt(
                tokenizer,
                build_messages(
                    item,
                    base_by_id[int(item["id"])],
                    args.mode,
                    args.base_tail_chars,
                    candidate_results,
                    args.candidate_tail_chars,
                ),
                disable_thinking=args.disable_thinking,
            )
            for item in batch
        ]
        if args.boxed_prefill:
            prompts = [apply_boxed_prefill(prompt) for prompt in prompts]

        if args.backend == "vllm":
            outputs = model.generate(prompts, sampling_params, lora_request=lora_request)
            raw_responses = [output.outputs[0].text.strip() for output in outputs]
        else:
            encoded = tokenizer(
                prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=args.max_model_len,
            ).to(model.device)
            import torch

            with torch.no_grad():
                output_ids = model.generate(
                    **encoded,
                    max_new_tokens=args.max_tokens,
                    do_sample=False,
                    pad_token_id=tokenizer.pad_token_id,
                )
            raw_responses = [
                tokenizer.decode(
                    output[encoded["input_ids"].shape[1] :],
                    skip_special_tokens=True,
                ).strip()
                for output in output_ids
            ]
        if args.boxed_prefill:
            raw_responses = [restore_boxed_prefill(response) for response in raw_responses]

        for item, raw_response in zip(batch, raw_responses):
            base_row = base_by_id[int(item["id"])]
            all_rows.append(
                {
                    "id": item["id"],
                    "is_mcq": bool(item.get("options")),
                    "response": coerce_boxed_response(raw_response),
                    "raw_qwen_response": raw_response,
                    "base_response": base_row.get("response", ""),
                    "qwen_pass_mode": args.mode,
                    "qwen_model": args.model,
                    "qwen_candidate_sources": sorted(candidate_results),
                    "disable_thinking": args.disable_thinking,
                    "boxed_prefill": args.boxed_prefill,
                    "legal_note": (
                        "Qwen-only generation pass; no solver, tool, API, "
                        "calculator, or deterministic answer computation."
                    ),
                }
            )
        write_jsonl(args.output, sorted(all_rows, key=lambda row: int(row["id"])))

    print(
        json.dumps(
            {
                "kaggle_upload": "not_performed",
                "output": str(args.output),
                "rows": len(all_rows),
                "model": args.model,
                "mode": args.mode,
                "disable_thinking": args.disable_thinking,
                "boxed_prefill": args.boxed_prefill,
                "compliance_mode": "legal_qwen_model_only_boxed_pass",
            },
            indent=2,
        ),
        flush=True,
    )
    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=DESIGNATED_MODEL)
    parser.add_argument("--backend", choices=["transformers", "vllm"], default="vllm")
    parser.add_argument("--data", type=Path, default=ROOT / "kaggle_data/private.jsonl")
    parser.add_argument("--base-results", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--question-filter", choices=["all", "mcq", "freeform"], default="all")
    parser.add_argument("--ids", default="")
    parser.add_argument("--ids-file", type=Path)
    parser.add_argument("--start-index", type=int, default=0)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--batch-size", type=int, default=24)
    parser.add_argument("--max-tokens", type=int, default=256)
    parser.add_argument("--max-model-len", type=int, default=8192)
    parser.add_argument("--dtype", default="auto")
    parser.add_argument("--gpu-memory-utilization", type=float, default=0.90)
    parser.add_argument("--vllm-max-num-seqs", type=int, default=32)
    parser.add_argument("--vllm-max-num-batched-tokens", type=int, default=32768)
    parser.add_argument("--vllm-max-lora-rank", type=int, default=64)
    parser.add_argument("--mode", choices=sorted(MODE_INSTRUCTIONS), default="format")
    parser.add_argument("--base-tail-chars", type=int, default=2400)
    parser.add_argument(
        "--candidate-results",
        nargs="*",
        default=[],
        help=(
            "Additional legal candidate JSONLs for --mode choose, supplied as "
            "name=path. The model sees their generated responses and chooses "
            "one answer; Python does not score or solve."
        ),
    )
    parser.add_argument("--candidate-tail-chars", type=int, default=900)
    parser.add_argument("--gpu-id")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument(
        "--boxed-prefill",
        action="store_true",
        help="Append an assistant \\boxed{ prefix before decoding, then restore the wrapper.",
    )
    parser.add_argument("--no-score", action="store_true", help="Accepted for compatibility; qwen.py never scores private rows.")
    parser.add_argument(
        "--disable-thinking",
        dest="disable_thinking",
        action="store_true",
        default=True,
        help="Disable Qwen thinking in the additional boxed pass. This is the default.",
    )
    parser.add_argument(
        "--enable-thinking",
        dest="disable_thinking",
        action="store_false",
        help="Opt into thinking for experiments. Do not use for the requested direct boxed pass.",
    )
    return parser


def main() -> int:
    return run_qwen_pass(build_arg_parser().parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
